/* tslint:disable */
require("./KnowledgeExplorer.module.css");
const styles = {
  explorer: 'explorer_bfa9193f',
  headerRow: 'headerRow_bfa9193f',
  breadcrumb: 'breadcrumb_bfa9193f',
  breadcrumbSegment: 'breadcrumbSegment_bfa9193f',
  breadcrumbSep: 'breadcrumbSep_bfa9193f',
  breadcrumbButton: 'breadcrumbButton_bfa9193f',
  backButton: 'backButton_bfa9193f',
  loading: 'loading_bfa9193f',
  emptyState: 'emptyState_bfa9193f',
  grid: 'grid_bfa9193f',
  folderCard: 'folderCard_bfa9193f',
  folderCardMain: 'folderCardMain_bfa9193f',
  folderMenuButton: 'folderMenuButton_bfa9193f',
  imagePickerCallout: 'imagePickerCallout_bfa9193f',
  imagePickerTitle: 'imagePickerTitle_bfa9193f',
  imagePickerPreview: 'imagePickerPreview_bfa9193f',
  imagePickerHint: 'imagePickerHint_bfa9193f',
  imagePickerRemove: 'imagePickerRemove_bfa9193f',
  folderMedia: 'folderMedia_bfa9193f',
  folderBadge: 'folderBadge_bfa9193f',
  folderIcon: 'folderIcon_bfa9193f',
  folderImage: 'folderImage_bfa9193f',
  folderName: 'folderName_bfa9193f',
  fileList: 'fileList_bfa9193f',
  fileListHeader: 'fileListHeader_bfa9193f',
  fileHeaderName: 'fileHeaderName_bfa9193f',
  fileHeaderCell: 'fileHeaderCell_bfa9193f',
  fileRow: 'fileRow_bfa9193f',
  fileNameCell: 'fileNameCell_bfa9193f',
  fileCell: 'fileCell_bfa9193f',
  fileIcon: 'fileIcon_bfa9193f',
  iconPdf: 'iconPdf_bfa9193f',
  iconDoc: 'iconDoc_bfa9193f',
  iconXls: 'iconXls_bfa9193f',
  iconPpt: 'iconPpt_bfa9193f',
  iconGeneric: 'iconGeneric_bfa9193f',
  fileInfo: 'fileInfo_bfa9193f',
  fileName: 'fileName_bfa9193f',
  fileMeta: 'fileMeta_bfa9193f'
};

export default styles;
/* tslint:enable */